---
title: "Wrangling Data in R"
output: 
  github_document: 
    toc: yes
---

This is the `README.md` file for the Katacoda scenario titled, "Wrangling Data in R"

## intro

This scenario will show you how to wrangle variables (columns) from one type to another. Data are rarely collected in a format they can be immediately analyzed or visualized in, so this is a common task.

## Variable types

Recall that variables can be characters, logical, numbers (integer and double). We will be converting variables from one form to another using [`dplyr`](https://dplyr.tidyverse.org/), a package from the [`tidyverse`](https://www.tidyverse.org/).

## step1

~~~
Launch the R REPL with `R`{{execute}}

Install and load the `tidyverse` package.

```
# packages
install.packages(c("tidyverse", "babynames"))
library(tidyverse)
```{{execute}}

When using a function from a package, the syntax is `package::function()`. We will use the `tibble` package to create the `BpData` dataset with the code below.

To view the contents of `BpData`, you simply enter the name into the console and a preview of the data will print to the Terminal.

```
# create BpData data
BpData <- tibble::tribble(
    # variable names ---------------------------------------------------------
         ~name,         ~dob, ~weight_kilos, ~height_meters, ~bp_dia, ~bp_sys,
    # data  ------------------------------------------------------------------
        "john", "1985-10-13",          100L,            '2.1',     80L,    130L,
       "peter", "1979-08-04",           82L,            '1.9',     65L,    126L,
       "steve", "1981-04-23",           95L,            '1.7',     70L,    119L,
       "sally", "1983-03-28",           72L,            '1.5',     75L,    129L,
        "beth", "1986-06-07",           76L,            '1.6',     78L,    126L,
        "kate", "1982-08-19",           69L,            '1.5',     74L,    121L)
# print data
BpData
```{{execute}}

~~~

## step2

~~~

```
# load data
EconDataWide <- ggplot2::economics
EconDataWide %>% glimpse(78)

# change structure
tidyr::pivot_longer()
```

~~~

## step3

~~~
```

```
~~~

## step4

## step5

## finish

***

## Appendix 1: Katacoda scenario tutorials

The tutorial for building the scenario is [here](https://katacoda.com/scenario-examples/scenarios/create-scenario-101).

I took notes on this tutorial and made them available in [this Google document](https://docs.google.com/document/d/e/2PACX-1vSf2w2onhH5t3IhuD4sYLoWqn46BLKMYFR7q3BHO8QTaRkVgXfhKvnl8T9uHrjmbVpTZVKCWrfxEl0R/pub).

## Appendix 2: Katacoda guidelines

There are multiple guidelines and resources for writing scenarios. O'Reilly has provided an *Authoring Guide* and *Formatting and Design Guide*.

The link for these files can be found here:

+ [Katacoda Scenario Formatting and Design Guide for Authors](https://docs.google.com/document/d/1l4lofG5kAu8JFzumZPCsJJE2muCYe6rHSHCQsMlijd8/edit)

+ [Katacoda Scenario Authoring Guide](https://docs.google.com/document/d/14rudtruZQhRxvD3zcR3g75j5nuOgKGz4CYk8hdhaV-w/edit)

## Appendix 3: Scenario Checklist

**Scenario Readiness Checklist:**

When you think your scenario is ready for publication, we recommend you run through the checklist below to ensure it is ready to go. [Reminder: We discuss these best practices in the Katacoda Formatting and Design Guide for Authors]:

Does the scenario start consistently and in a timely manner? More than 5 minutes to start would be cause to reconsider your build decisions.

- [ ] Are your intro and final pages present and are their respective goals and lessons learned in agreement?

- [ ] Have you tested your scenario lately?

- [ ] Do you agree with the leveling (beginner, intermediate, advanced) you indicated when you started the build?

- [ ] Was learning time you entered correct, or should it be adjusted?

- [ ] Are your versions of tools and other dependencies up to date?

- [ ] Have you tried every instruction?

- [ ] Have you written each step in the most concise manner possible?

- [ ] Have you run your text through a spelling/grammar checker?

- [ ] Are your credits to others given present and correct?

- [ ] Are your images legal and with credits?

- [ ] Are your hyperlinks all working?

- [ ] Do the goals and lessons learned items match the steps in the scenario?


## Scenario contents

This scenario covers...




