---
title: "Katacoda scenarios"
output: 
  github_document: 
    toc_depth: 6
    
always_allow_html: true
---

This is the `README` file for the Katacoda scenarios. All the scenarios and courses can be found on my profile page [here](https://katacoda.com/mjfrigaard).

Link to Github repo: https://resources.oreilly.com/katacoda/martin-frigaard

## The `index.json` file 

The environment for the scenario's creating images (i.e. graphs) should look like this: 

```json
  "environment": {
    "uilayout": "vscode-terminal-split",
    "showide": true
  },
```


## Format and shape your data with R in the tidyverse

- [x] on gitlab? 
- [x] tested? 
- [x] reviewed? 

Link to scenario: https://katacoda.com/orm-mfrigaard/scenarios/01-format-shape-data

Link to Github repo: https://resources.oreilly.com/katacoda/martin-frigaard

## Introduction to the grammar of graphics

- [x] on gitlab? 
- [x] tested? 
- [x] reviewed? 

Link to scenario: https://www.katacoda.com/orm-mfrigaard/scenarios/02-intro-ggplot2

Link to Github repo: https://resources.oreilly.com/katacoda/martin-frigaard


## How to Create Column Charts in R with ggplot2

- [x] on gitlab? 
- [x] tested? 
- [x] reviewed? 

**slug:** how-to-create-column-charts-in-r-with-ggplot2

**description:** Display counts with column charts

## How to Create Bar Charts in R with ggplot2

- [x] on gitlab? 
- [x] tested? 
- [x] reviewed? 

**slug:** how-to-create-bar-charts-in-r-with-ggplot2

**description:** Display counts with bar charts

## How to Create Histograms in R with ggplot2

- [x] on gitlab? 
- [x] tested? 
- [x] reviewed? 

**slug:** how-to-create-histograms-in-r-with-ggplot2

**description:** View single variable distributions with histograms

## How to Create Density Plots in R with ggplot2

- [x] on gitlab? 
- [x] tested? 
- [x] reviewed? 

**slug:** how-to-create-density-plots-in-r-with-ggplot2

**description:** View single variable distributions with density plots 


## How to Create Ridgeline Plots in R with ggridges

- [x] on gitlab? 
- [x] tested? 
- [x] reviewed? 

**slug:** how-to-create-ridgeline-plots-in-r-with-ggridges

**description:** View multiple variable distributions with ridgeline plots


## How to Create Boxplots in R with ggplot2

- [x] on gitlab? 
- [x] tested? 
- [x] reviewed? 

**slug:** how-to-create-boxplots-in-r-with-ggplot2

**description:** View multiple variable distributions with boxplots plots


## How to Create Scatter-plots  in R with ggplot2

- [x] on gitlab? 
- [x] tested? 
- [x] reviewed? 

**slug:** how-to-create-scatter-plots--in-r-with-ggplot2

**description:** View relationships between variables with scatter plots


## How to Create Line-plots in R with ggplot2

- [x] on gitlab? 
- [x] tested? 
- [x] reviewed? 

**slug:** how-to-create-line-plots-in-r-with-ggplot2

**description:** View trends over time with line-plots


## How to Create Jitter plots in R with ggplot2

- [x] on gitlab? 
- [x] tested? 
- [x] reviewed? 

**slug:** how-to-create-jitter-plots-in-r-with-ggplot2

**description:** Add noise to a scatter plot with jitter plots


## How to Create Small Multiples in R with ggplot2

- [x] on gitlab? 
- [x] tested? 
- [x] reviewed? 

**slug:** how-to-create-small-multiples-in-r-with-ggplot2

**description:** Arrange multiple graphs in a grid layout with small multiples

***

## Resources

- The Supported Layouts: This is the [documentation](https://www.katacoda.community/layouts.html) for the supported layouts

- UI Layouts Examples: These are the supported [UI layouts](https://katacoda.com/scenario-examples/courses/uilayouts). 

The two UI layouts that look the most promising are the [Scenario with Terminal iFrame UI](https://katacoda.com/scenario-examples/courses/uilayouts/uilayout-terminal-iframe) and the [Visualise Environment Tab](https://katacoda.com/scenario-examples/courses/uilayouts/visualise-docker)
